### PR TITLE
Add rwmutex to connection established.

### PR DESCRIPTION
**Pull request by iwanbk**
We need this to prevent data race happened when running more than one router in the same application process, i got it in my unit test

Below is the data race error message that fixed by this PR
```go
WARNING: DATA RACE
Read at 0x00c000188031 by goroutine 30:
  github.com/weaveworks/mesh.(*LocalConnection).isEstablished()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/connection.go:122 +0x3e
  github.com/weaveworks/mesh.(*Peer).encode()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/peers.go:532 +0x244
  github.com/weaveworks/mesh.(*localPeer).encode()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/local_peer.go:133 +0x92
  github.com/weaveworks/mesh.(*Peers).encodePeers()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/peers.go:398 +0x240
  github.com/weaveworks/mesh.(*topologyGossipData).Encode()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/router.go:311 +0x74
  github.com/weaveworks/mesh.(*gossipSender).deliver()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip.go:144 +0xac
  github.com/weaveworks/mesh.(*gossipSender).run()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip.go:105 +0x207

Previous write at 0x00c000188031 by goroutine 20:
  github.com/weaveworks/mesh.(*LocalConnection).actorLoop()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/connection.go:358 +0x3dd
  github.com/weaveworks/mesh.(*LocalConnection).run()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/connection.go:256 +0xc13

Goroutine 30 (running) created at:
  github.com/weaveworks/mesh.newGossipSender()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip.go:94 +0x238
  github.com/weaveworks/mesh.(*gossipChannel).makeGossipSender()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip_channel.go:126 +0x11c
  github.com/weaveworks/mesh.(*gossipChannel).makeGossipSender-fm()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip_channel.go:122 +0x5f
  github.com/weaveworks/mesh.(*gossipSenders).Sender()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip.go:247 +0x178
  github.com/weaveworks/mesh.(*gossipChannel).senderFor()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip_channel.go:122 +0xc7
  github.com/weaveworks/mesh.(*gossipChannel).SendDown()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/gossip_channel.go:93 +0x4c
  github.com/weaveworks/mesh.(*Router).sendAllGossipDown()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/router.go:208 +0x133
  github.com/weaveworks/mesh.(*localPeer).handleAddConnection()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/local_peer.go:191 +0x581
  github.com/weaveworks/mesh.(*localPeer).doAddConnection.func1()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/local_peer.go:108 +0x68
  github.com/weaveworks/mesh.(*localPeer).actorLoop()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/local_peer.go:143 +0x144

Goroutine 20 (running) created at:
  github.com/weaveworks/mesh.startLocalConnection()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/connection.go:99 +0x4c7
  github.com/weaveworks/mesh.(*localPeer).createConnection()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/local_peer.go:98 +0x2a3
  github.com/weaveworks/mesh.(*connectionMaker).attemptConnection()
      /Users/ibk/pathgo/src/github.com/weaveworks/mesh/connection_maker.go:375 +0x21f
```

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for this!  I see the race very clearly from your report.  (there was already a [comment](https://github.com/weaveworks/mesh/blob/61ba45522f8a5ac096d36674144357341b8ccea9/connection.go#L120) noting it)

However, the "actor" model used in much of this package is explicitly chosen to avoid the use of mutexes, therefore I will not merge this right away.

Further thought and consideration is required.

**Comment by iwanbk** [comment]
> However, the "actor" model used in much of this package is explicitly chosen to avoid the use of mutexes, therefore I will not merge this right away.

didn't know about it, i'll investigate it further

**Comment by bboreham** [comment]
@iwanbk if you like videos you can watch me explain the whole idea here https://www.gophercon.co.uk/videos/2016/an-actor-model-in-go/

**Comment by iwanbk** [comment]
@bboreham 
thanks for the video, watched it yesterday, really good talks!

After watching your presentation, i modified the `func` a little bit, to be something like this
```go
func (conn *LocalConnection) isEstablished() bool {
    resultCh := make(chan bool)
    conn.actionChan <- func() {
        resultCh <- conn.established
    }
    return <-resultCh
}
```
but after some debugging, i found that the `actorLoop`

https://github.com/weaveworks/mesh/blob/37eda87db313436ac71550edbac6d6b4786ffbb2/connection.go#L345-L346

haven't been executed even after my unit test finished.

I'll check it more, i think i can learn a lot from this repo

**Comment by bboreham** [comment]
I'll close this rather than leave it hanging around: it needs more work.  Happy to re-open if you come back to it.

**Pull request closed without merging**
