### PR TITLE
Panics on null overlay

### PR DESCRIPTION
**Pull request by zignig**
added nil check for encrypted attr

### CODE REVIEW

**Comment by rade** [comment]
Have you run into this? How?

**Comment by zignig** [comment]
After doing a vendor upgrade for (https://github.com/zignig/mfsrepl) , I was getting a panic when any node was not accessible on my mesh.

Looked through the code and found that the attrs returned for a NullOverlay (not using them, yet :) ) gave me a panic.

It was happening when there was a mesh and one of the existing nodes failed

trace 

panic: assignment to entry in nil map

goroutine 8 [running]:
github.com/weaveworks/mesh.makeLocalConnectionStatusSlice.func1(0xc42003af40)
	/opt/mfsrepl/vendor/src/github.com/weaveworks/mesh/status.go:179 +0x42f
github.com/weaveworks/mesh.(*connectionMaker).queryLoop(0xc420020e00, 0xc420062960)
	/opt/mfsrepl/vendor/src/github.com/weaveworks/mesh/connection_maker.go:228 +0xf6
created by github.com/weaveworks/mesh.newConnectionMaker
	/opt/mfsrepl/vendor/src/github.com/weaveworks/mesh/connection_maker.go:75 +0x21a

**Comment by zignig** [comment]
If you would like any more debug ...

**Comment by zignig** [comment]
It appears to happen when the mesh times out an inaccessible node.

**Comment by rade** [comment]
@zignig Well spotted. Thanks for your contribution. Merged.

**Pull request merged**
